# database setup
spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://172.21.0.2:5432/notification_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    # Session Metrics : JDBC connections, L2C puts, hits, misses, Flushes, partial-flushes
    properties:
      hibernate:
#        generate_statistics: true
#        format_sql: true
web:
  cors:
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS, PATCH, HEAD
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"
logging:
  level:
    org:
      springframework:
        #        security: debug    # spring security logging
        web:
          cors: debug       # CORS debugging
management:
  endpoints:
    web:
      exposure:
        include: security
# cors configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173, http://127.0.0.1:5173}





